name: 'Terraform WorkFlow'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID:    ${{ secrets.AZURE_CLIENT_ID }} 
  ARM_CLIENT_SECRET:    ${{ secrets.AZURE_CLIENT_SECRET }} 
  ARM_SUBSCRIPTION_ID:    ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ secrets.Azure_TENANT_ID }}

jobs:
  terraform_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Formatting
        run: terraform fmt -check
      
      - name: Terraform Validate
        run: terraform validate

  terraform_plan:
    needs: terraform_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
       
      - name: Save Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
         name: terraform-plan
         path: tfplan

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
         name: terraform-plan
         path: .

      - name: Apply the terraform plan
        run: terraform apply -auto-approve tfplan